# Generated by Django 2.0.6 on 2018-10-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0003_expenses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timeOfTransaction', models.DateTimeField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='checking',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='balanceHistory',
            new_name='timeAccountCreated',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
        migrations.AddField(
            model_name='expenses',
            name='emergencyFund',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
