# Generated by Django 2.0.6 on 2018-10-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_transactions_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='checking',
            new_name='balance',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
